[#1532] Displaying toolType in tool sheet header
foundryvtt/dnd5e pull request #1710
Opened 2022-08-18 21:14 UTC by djinnstar

[possible solution to #1532]

This PR adds the tool's type [from among Artisan's, Musical Instrument, or Gaming Set] to the tool sheet's header.

2022-08-18 22:32 UTC, arbron requested changes
I think the handling of non-typed tools got lost in the shuffle :).

2022-08-18 22:32 UTC, arbron commented on templates/items/tool.hbs
> +                    {{lookup config.toolTypes system.toolType}}
```suggestion
                    {{#if system.toolType}}
                      {{lookup config.toolTypes system.toolType}}
                    {{else}}
                      {{localize "DND5E.ItemTypeTool"}}
                    {{/if}}
```

2022-08-18 22:47 UTC, djinnstar commented
Good point! Added back in.

2022-08-19 17:11 UTC, arbron approved these changes

2022-08-19 17:21 UTC, merged