refactor: centralize fastforward detection for roll configs
foundryvtt/dnd5e pull request #1828
Opened 2022-09-24 17:57 UTC by akrigline

## Goals
1. Centralize `fastForward` and `critical` detection within the `dice.mjs` helper functions, rather than also have some event key detection within `rollDamage` and similar methods.
    - `_determineCriticalMode` and `_determineAdvantageMode` should be the only methods concerned with determining these roll modifiers to make it easier to refactor those methods later (e.g. in #1591)
2. Respect when `damageRoll` or `d20Roll` is invoked with `fastForward` explicitly set to `false`, showing the roll config dialog as normal.
3. Maintain the current API call signatures and behaviors, except in the case where `fastForward` is explicitly set to false.

### Problem being Solved

> It is not possible to explicitly override a roll config to be `fastForward: false` if the config also has an `event` which would normally fast-forward a roll config.

<details>
<summary>Example scenario</summary>

```javascript
item.rollAttack({ event: { altKey: true }, fastForward: false, advantage: true });
```
As an API consumer I expect the attack roll configuration dialog to appear, but with `advantage` as the default button (This is the current behavior if I leave out the `event`):

![Demonstration of the expectation working with this PR's code changes](https://user-images.githubusercontent.com/7644614/192112005-3d702d8e-9d39-4a34-b0f5-f42e9865b9b6.png)

When the `event` is populated, the `fastForward: false` is ignored because of the `event` handling in various places of the workflow.
</details>

### Methodology

Remove the `event` checking that happened during item damage and attack roll workflows (from `_onChatCardAction` and `rollDamage`).

Remove the defaults for the `critical` and `fastForward` booleans from all methods/configs, allowing them to be `undefined` until `_determineAdvantageMode` and `_determineCriticalMode`'s evaluation (this did not affect `d20Roll`'s `critical` number argument).

2022-10-07 12:21 UTC, Fyorl requested changes

2022-10-07 12:21 UTC, Fyorl commented on module/dice/dice.mjs
> + * @property {boolean} [fastForward]     Should the roll configuration dialog be skipped?
```suggestion
 * @property {boolean} [fastForward]           Should the roll configuration dialog be skipped?
```

2022-10-07 12:21 UTC, Fyorl commented on module/dice/dice.mjs
> + * @property {boolean} [critical]      Apply critical to this roll (unless overridden by modifier key or dialog)?
```suggestion
 * @property {boolean} [critical]            Apply critical to this roll (unless overridden by modifier key or dialog)?
```

2022-10-07 12:21 UTC, Fyorl commented on module/dice/dice.mjs
> + * @property {boolean} [fastForward]  Should the roll configuration dialog be skipped?
```suggestion
 * @property {boolean} [fastForward]        Should the roll configuration dialog be skipped?
```

2022-10-07 12:21 UTC, Fyorl commented on module/documents/item.mjs
> +    debugger;
Leftover `debugger` statement.

2022-10-07 19:57 UTC, akrigline commented on module/documents/item.mjs
> +    debugger;
```suggestion
```

2022-10-08 12:52 UTC, Fyorl approved these changes

2022-10-08 12:52 UTC, merged