[#1834] Implement Forgotten Adventures token packs 37 through 39
foundryvtt/dnd5e pull request #1918
Opened 2022-11-04 09:48 UTC by kjolern

I have added the Forgotten Adventures token packs 37,38 and 39. Fixes #1834

The following tokens was added: 
Ox - Token added.  Not in use since no Ox monster exists yet
Solar - Active
Solar with bow - Token added. Not in use sin Solar is Active
Flesh Golem - Active
Wyvern - Active
Young Blue Dragon - Active
Young Brass Dragon - Active
Young Copper Dragon - Active
Cloud Giant - Active
Ettin - Active
Hill Giant - Active
Half-Red Dragon Veteran - Active 
Merfolk Mermaid - Token added. Not in use since no Merfolk mermaid exists yet. Merfolk is already set up
Merfolk Mermaid Underwater - Token added. Not in use since no Merfolk mermaid exists yet. Merfolk is already set up
Androsphinx - Active
Shambling Mound - Active
Treant - Active
Ogre Zombie - Active
Skeleton armed - Token added. Not in use since skeleton is already set up.
Skeleton clothes - Token added. Not in use since skeleton is already set up.
![icons](https://user-images.githubusercontent.com/79190020/199943248-711f68c6-611f-45b5-af88-864a80a94d9f.png)

2022-11-04 14:11 UTC, aaclayton commented
Looks like a good start, a few things that still need addressing:

1. Many token sizes or scales are not correct. Many of these tokens are oversized and need to receive a specific scale greater than one. The correct scale to use is provided by FA as part of the token name.

2. Each actor needs the following HTML placed at the end of its biography.

```html
<p><em>Token artwork by Forgotten Adventures.</em></p>
```

2022-11-04 14:11 UTC, aaclayton requested changes
Looks like a good start, a few things that still need addressing:

1. Many token sizes or scales are not correct. Many of these tokens are oversized and need to receive a specific scale greater than one. The correct scale to use is provided by FA as part of the token name.

2. Each actor needs the following HTML placed at the end of its biography.

```html
<p><em>Token artwork by Forgotten Adventures.</em></p>
```

2022-11-07 22:53 UTC, kjolern commented
I think I got the scales right. I guess 166 in the file name means 1,66 on the scale like the fire giant had. I have also added mentions for Forgotten Adventures in the bio. Let me know if further changes are needed @aaclayton

2022-12-02 16:51 UTC, Fyorl approved these changes

2022-12-02 16:51 UTC, merged