[#1605] Prepare scale values earlier to allow them to be modified by active effects
foundryvtt/dnd5e pull request #2011
Opened 2023-01-02 06:30 UTC by arbron

Moves the data preparation for scale value into `Actor5e#prepareBaseData` so they can be modified by active effects. This also allows them to be used as in input for an active effect if a player is using a module like DAE. In order to accomplish this we needed to perform advancement preparation earlier so this introduces `Item5e#prepareInitialAttributes` to mirror `Item5e#prepareFinalAttributes` so that can be done before other actor data preparation.

2023-01-13 20:44 UTC, Fyorl commented
A couple of high-level design issues that bear discussing before I review:

1. We have a longstanding issue in the system whereby some active effects are intended to modify values *before* calculations are done. For example, an AE that modifies an ability score would want that modification reflected in that ability's derived `mod` value. Some active effects are intended to modify values *after* calculations are done. For example, an AE that modifies `ac.value` would want that modification done after the `ac.value` has already been calculated so that it is not subsequently overridden as part of normal data preparation.

It seems to me that that this line lies along the base/derived line. An AE targeting a base field should probably be applied before derived data is calculated, and an AE targeting a derived field should probably be applied afterwards, but I don't know if that's true in all cases. If it is true though, then we have a clear path to providing a smart AE system that could be quite powerful.

The question, then, is does this proposal fit into that? If we do the above work, would this particular issue be solved as part of that?

2. If this issue would not be solved by some wider work on AEs in general, is there a solution that does not involve looping over all embedded items twice on every data preparation? The answer might be no but data preparation is not free and can become hot code in certain contexts (migrations, world initialisation) so we should try to be frugal where we can.

2023-01-15 23:04 UTC, arbron commented
@Fyorl Upon further examination of how `Actor` is implemented in core, I've realized that there is a simpler way to implement this. The only thing that needs to happen is we need to prepare these scale values after `Item#prepareData` is called but before active effects are applied, so no need to loop over items again.

2023-01-16 19:10 UTC, Fyorl requested changes

2023-01-16 19:10 UTC, Fyorl commented on module/documents/actor/actor.mjs
> +    super.prepareEmbeddedDocuments();
This call to `super.prepareEmbeddedDocuments` (in this case `Actor#prepareEmbeddedDocuments`) will also call `this.applyActiveEffects`, no? I suppose we could move `this._prepareScaleValues` to the top of the `applyActiveEffects` override instead?

2023-01-20 17:22 UTC, Fyorl approved these changes

2023-01-20 17:22 UTC, merged