[#2071] Default to metric length units for movement and senses
foundryvtt/dnd5e pull request #2073
Opened 2023-01-17 20:50 UTC by arbron

2023-01-20 18:40 UTC, Fyorl approved these changes

2023-01-20 18:49 UTC, Fyorl requested changes
A couple of things we need to address first, I think:
1. Our setting is currently `metricWeightUnits`, and is labelled as such in the settings screen. If we want to handle distance units, we should add a separate setting for that. I do think this should be two separate settings because, for whatever reason, some localised versions of the rules mix metric distances with imperial weights and vice versa (even if the country in question does not use imperial measurements for anything).
2. There's not currently any way (that I can see) where a user can change the movement units for an actor. It seems to only be possible via the API.

2023-01-20 19:11 UTC, arbron commented
> 1. Our setting is currently `metricWeightUnits`, and is labelled as such in the settings screen. If we want to handle distance units, we should add a separate setting for that. I do think this should be two separate settings because, for whatever reason, some localised versions of the rules mix metric distances with imperial weights and vice versa (even if the country in question does not use imperial measurements for anything).

I can see that, I'll push this off to `2.2` since it is growing in scope.

> 2. There's not currently any way (that I can see) where a user can change the movement units for an actor. It seems to only be possible via the API.

That's another bug that is fixed in #2072

2024-12-12 17:59 UTC, Fyorl requested changes
Looks good, I just have one thing that I'm not sure about. For senses and speeds we have a drop-down of units, and one of the options is 'automatic'. If a content module is packaging monsters with all their speeds and senses set to automatic, will that mean that they have 60ft Darkvision when imported into an imperial world, and 60m Darkvision when imported into a metric World? This can't be a new problem though, it must already be the case?

Should we remove this 'automatic' option now and instead have the drop-down default to the `defaultUnit("length")`? This would be the same as weapon and spell ranges, and item weights, which require a unit, so they do not have this problem.

2024-12-12 18:05 UTC, arbron commented
> Looks good, I just have one thing that I'm not sure about. For senses and speeds we have a drop-down of units, and one of the options is 'automatic'. If a content module is packaging monsters with all their speeds and senses set to automatic, will that mean that they have 60ft Darkvision when imported into an imperial world, and 60m Darkvision when imported into a metric World? This can't be a new problem though, it must already be the case?
> 
> Should we remove this 'automatic' option now and instead have the drop-down default to the `defaultUnit("length")`? This would be the same as weapon and spell ranges, and item weights, which require a unit, so they do not have this problem.

I'll take a look at it, but I think that might have been an unintended consequence of sharing the dialog between actors and species. It feels like the correct behavior is to have automatic only for when the dialog is shown from actor sheets, but require units for species sheets.

2024-12-12 19:56 UTC, Fyorl commented
> I'll take a look at it, but I think that might have been an unintended consequence of sharing the dialog between actors and species. It feels like the correct behavior is to have automatic only for when the dialog is shown from actor sheets, but require units for species sheets.

Doesn't the issue still exist for NPCs? They don't get their senses and speed from a species item (unless manually added). If the data I am inputting says the creature has a speed of 30 feet, I should of course set the unit explicitly to feet, but the drop-down kind of implies that I don't have to do that since it says 'Automatic (feet)'. But if this creature is included in a module and then imported into a World set to metric, then that creature suddenly has a speed of 30m no?

2024-12-12 21:22 UTC, arbron commented
> Doesn't the issue still exist for NPCs? They don't get their senses and speed from a species item (unless manually added). If the data I am inputting says the creature has a speed of 30 feet, I should of course set the unit explicitly to feet, but the drop-down kind of implies that I don't have to do that since it says 'Automatic (feet)'. But if this creature is included in a module and then imported into a World set to metric, then that creature suddenly has a speed of 30m no?

Adjusted

2024-12-13 15:37 UTC, Fyorl approved these changes

2024-12-13 18:23 UTC, merged