[#2036] Add physical properties to ammunition
foundryvtt/dnd5e pull request #2117
Opened 2023-01-26 22:20 UTC by arbron

Enables setting of physical properties on ammunition (e.g. "Adamantine", "Magical", or "Silvered").

2023-05-27 11:53 UTC, krbz999 commented
Related issue: https://github.com/foundryvtt/dnd5e/issues/1088

2023-06-12 15:34 UTC, Fyorl requested changes

2023-06-12 15:34 UTC, Fyorl commented on templates/items/consumable.hbs
> +                    <input type="checkbox" name="system.properties.{{prop}}" {{checked (lookup ../system.properties prop)}}/> {{ name }}
This was probably done for consistency, but we should try avoid legacy self-closing tags on void elements going forward.

```suggestion
                    <input type="checkbox" name="system.properties.{{prop}}" {{checked (lookup ../system.properties prop)}}> {{ name }}
```

2023-07-11 18:18 UTC, Fyorl approved these changes

2023-07-11 18:19 UTC, merged