[#1403] Ability Score Improvement Advancement
foundryvtt/dnd5e pull request #2158
Opened 2023-02-06 20:37 UTC by arbron

Implements the ability score improvement advancement to allow for selecting ability scores and feats.

![Rogue - Advancements](https://user-images.githubusercontent.com/19979839/217078924-cc8b940a-358a-4912-aa2a-04a0d0146cf8.jpg)

### Configuration

The ability score improvement can be configured to allow for a number of variable points that can be assigned as the user chooses (like with classes):

![Configure Points Improvement](https://user-images.githubusercontent.com/19979839/217079084-546032a5-b660-430f-9e3a-0aaaff2e2d23.jpg)

Or with a fixed improvement to certain traits:

![Configure Fixed Improvement](https://user-images.githubusercontent.com/19979839/217079147-80372bdc-25bd-42d8-9a34-dd755927eff6.jpg)

Or a combination of the two.

### Application

During the level up process the player is presented with a list of their ability scores with the ability to modify them:

![Apply Points Improvement](https://user-images.githubusercontent.com/19979839/217079342-0a16ffea-ab5f-4447-afd1-b461e7bd579d.jpg)

When added to classes, the advancement also presents the option of selecting a feat:

https://user-images.githubusercontent.com/19979839/217079416-6d802657-995a-4bb1-8733-717464b6fb4d.mov

If a fixed improvement is configured, then that is indicated on the screen and those scores cannot be modified by the player:

![Apply Fixed Improvement](https://user-images.githubusercontent.com/19979839/217079585-7ce4d024-ec31-4559-b9bb-e5f6be02d5ab.jpg)

2023-04-03 15:02 UTC, Zanderaf commented
Any plans to add function with feats increasing ability scores when dragged in?  There arent any I know of off the top of my head in the SRD but stuff like Keen Mind has Int or Wis

2023-06-12 20:38 UTC, Fyorl requested changes
Really great stuff, Jeff. The code looks good, only some minor feedback, and in particular the UI looks very crisp and polished.

2023-06-12 20:38 UTC, Fyorl commented on module/applications/advancement/ability-score-improvement-config.mjs
> +        key: key,
```suggestion
        key,
```

2023-06-12 20:38 UTC, Fyorl commented on module/data/advancement/ability-score-improvement.mjs
> +      feat: new MappingField(new foundry.data.fields.StringField(), {
The fact that this is a `MappingField` is awkward, but I understand that it fits better into the rest of our framework around adding items via advancements.

2023-06-12 20:38 UTC, Fyorl commented on module/documents/advancement/ability-score-improvement.mjs
> +      assigned: Object.values(this.value.improvements ?? {}).reduce((n, c) => n + c, 0),
Should this be `assignments`?
```suggestion
      assigned: Object.values(this.value.assignments ?? {}).reduce((n, c) => n + c, 0),
```

2023-07-11 19:43 UTC, Fyorl approved these changes

2023-07-11 19:43 UTC, merged