Update spell-icon-migration.json for 'explosion-star' icons
foundryvtt/dnd5e pull request #2340
Opened 2023-06-08 15:50 UTC by M0nk3yy

Migration entries for `icons/magic/light/explosion...` are incorrect.

They are trying to convert paths that do exist such as `explosion-star-large-orange-purple` into paths that do not exist: `explosion-star-orange-purple-large`. This results in broken icon paths whenever the migration runs.

The core icons should probably be renamed so alike colours are next to each other and the schema is consistent. This is the case with other icons such as `beam-rays-orange-small.webp` where the size is at the end. Until that time, this change amends the migration to work with the current icon naming scheme.

Fixes #2360

2023-06-26 06:19 UTC, LukasPrism commented
After updating to 2.2.1 I’m experiencing the joy of fixing all the items again that broke in 2.1. Hopefully this isn’t still a problem in 2.3

2023-07-05 07:31 UTC, M0nk3yy commented
Fixes #2360

2023-07-05 08:55 UTC, M0nk3yy commented
@Fyorl Please consider this for 2.2.2 to prevent broken icon paths

2023-07-05 11:39 UTC, Fyorl commented on json/spell-icon-migration.json
> +  "icons/magic/light/explosion-star-blue-large.webp": "icons/magic/light/explosion-star-large-blue.webp",
I can see in both v10 and v11 that the icon is called `explosion-star-blue-large`, so this change would map a correct icon filename to an incorrect filename, no? It looks like the original line was correct. What am I missing here?

2023-07-05 11:55 UTC, Fyorl commented on json/spell-icon-migration.json
> +  "icons/magic/light/explosion-star-blue-large.webp": "icons/magic/light/explosion-star-large-blue.webp",
I think I picked the first line which just happened to be a mistake. The two `explosion-star-blue` lines need to be reverted, but I checked the other lines and they all seem to be correct.

2023-07-05 11:56 UTC, Fyorl requested changes
See comments about `explosion-star-blue`

2023-07-05 12:49 UTC, M0nk3yy reviewed
Changes to lines 414 and 415 reverted

2023-07-05 12:50 UTC, Fyorl approved these changes

2023-07-05 12:50 UTC, M0nk3yy commented
Thanks Kim, good catch. I hadn't spotted that those two use a different naming format. The changes have been made.

2023-07-05 12:51 UTC, merged