[#2136, #2153] Add multiple inline editors to items & display chat description
foundryvtt/dnd5e pull request #2527
Opened 2023-10-26 19:05 UTC by arbron

Adds multiple inline editors into items to allow editing normal description, unidentified description, and chat text. When the edit button is clicked the editor replaces the whole tab giving plenty of space to write.

https://github.com/foundryvtt/dnd5e/assets/19979839/09eb8de2-5b2b-409c-830c-5b9d3e559e50

This also will display the chat text in created chat messages rather than the default description if it is provided.

Closes #2136 
Closes #2153

2023-10-26 19:27 UTC, krbz999 commented
My artistic skills are offensive, but hear me out. Rather than elongating the description field possibly thrice over vertically, can we split it horizontally?

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/b732a749-ecb3-4606-a262-d33bdcac41de)

2023-10-30 16:57 UTC, Fyorl requested changes
Code looks good to me, just one comment. We do seem to be missing the actual accordion part of the 'accordion' design though. I've attached a diff that implements a (relatively) lightweight `Accordion` class to handle this, including some CSS transition animations. It will wrap any markup but we could maybe simplify things by mandating use of `<details>` elements.

https://github.com/foundryvtt/dnd5e/assets/207433/f8991122-5036-4916-bb68-170e516cffe6

Zhell raises a reasonable point that, with very long descriptions, we will have too much crammed into the pane. The implementation comes with a `collapseOthers` option that we could employ here to make better use of the space (this is the typical 'accordion' effect.)

https://github.com/foundryvtt/dnd5e/assets/207433/73b25b4a-c0cb-478d-8772-21d70ee4df68

At this point though, we should consider if going to all this effort is necessary when we could just leverage the existing tabs infrastructure.

Personally, I find it useful to be able to compare the descriptions and see them all at once. I also find it a bit more obvious which description is currently being edited when they are arranged vertically with headings in this way, rather than as tabs. I appreciate that these are fairly minor advantages, though I would hope that if we do opt to use the accordion widget, that it would open up some design space elsewhere also.

If we do decide to pursue this avenue, let me know if you'd prefer to incorporate the changes yourself referencing the diff, or if I should push a commit to this branch or something.

[accordion.patch](https://github.com/foundryvtt/dnd5e/files/13207767/accordion.patch)

2023-10-30 18:26 UTC, arbron commented
@Fyorl I merged your accordion changes in, with the `collapseOthers` set to `false` based on popular opinion. I also added a transition to `margin-bottom` to avoid that little jump that was happening :).

2023-10-31 18:36 UTC, Fyorl approved these changes

2023-10-31 18:37 UTC, merged