[#2504] Convert source on items into object
foundryvtt/dnd5e pull request #2534
Opened 2023-10-29 20:51 UTC by arbron

First part of #2504 that migrates the data structure to an object. This updates the existing templates to display and reference `source.custom` so a future PR can add a source configuration app.

```json
{
  book: "",
  page: "",
  custom: "",
  uuid: "",
  license: ""
}
```

2023-10-30 15:16 UTC, aaclayton requested changes
Looking good to me, thanks @arbron. Get any feedback from @Fyorl but this looks able to move forward.

2023-10-30 15:16 UTC, aaclayton commented on module/data/actor/npc.mjs
> +    source.details.source = { custom: source.details.source };
I think we need to be careful and ensure that `source.details.source` is present:
```suggestion
    if ( ("source" in source.details) && (foundry.utils.getType(source.details.source) !== "Object") ) {
      source.details.source = {custom: source.details.source};
    } 
```

2023-10-30 15:16 UTC, aaclayton commented on module/data/shared/source-field.mjs
> +        return this.custom ?? "";
Perhaps for now (can be improved later):
```suggestion
        return this.custom ?? `${this.book} ${this.page}`;
```

2023-10-30 15:16 UTC, aaclayton commented on module/data/shared/source-field.mjs
> +    Object.defineProperty(obj, "toString", {
Good call with assigning a `toString` redirect.

2023-10-31 19:25 UTC, Fyorl approved these changes

2023-10-31 19:29 UTC, merged