[#456] NPC Death Saves - Updated Schema and Sheet
foundryvtt/dnd5e pull request #2549
Opened 2023-11-03 21:22 UTC by kgar

Adds `death` schema to `NPCData`, "Death Saves" UI to the NPC sheet template, and the appropriate wiring for supporting NPC data-action "rollDeathSave".

2023-11-04 01:22 UTC, kgar commented
Here's what it looks like with the current template updates:

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/1cfa12a9-25e9-4449-96dd-c2dd8c594ede)

2024-02-23 22:48 UTC, arbron requested changes

2024-02-23 22:48 UTC, arbron commented on templates/actors/npc-sheet.hbs
> +                            <input type="text" name="system.attributes.death.failure" value="{{system.attributes.death.failure}}" placeholder="0" data-dtype="Number">
```suggestion
                            <i class="fa-solid fa-check"></i>
                            {{ numberInput system.attributes.death.success name="system.attributes.death.success"
                               min=0 step=1 placeholder=0 }}
                            <i class="fa-solid fa-times"></i>
                            {{ numberInput system.attributes.death.failure name="system.attributes.death.failure"
                               min=0 step=1 placeholder=0 }}
```

2024-02-24 04:04 UTC, arbron approved these changes

2024-02-24 04:06 UTC, merged