[#2591] Implement 'attackFlat' property
foundryvtt/dnd5e pull request #2592
Opened 2023-11-14 22:32 UTC by krbz999

Closes #2591.

Coincidentally, attack rolls with spell scrolls were adding proficiency bonuses unintentionally. This fixes that, too, as a side effect.

2024-02-21 23:09 UTC, arbron requested changes

2024-02-21 23:09 UTC, arbron commented on lang/en.json
> +"DND5E.ItemAttackFlatHint": "If checked, all bonuses except the value input here will be ignored.",
Probably need to make this a bit more explicit as excluding proficiency and ability modifiers:

```suggestion
"DND5E.ItemAttackFlatHint": "If checked, don't add proficiency, ability modifier, or any other bonuses to attack roll except what is included here.",
```

2024-02-21 23:09 UTC, arbron commented on templates/items/parts/item-action.hbs
> +        <input type="text" name="system.attack.bonus" value="{{system.attack.bonus}}" data-formula-editor/>
Gotta git rid of these pesky closing slashes :/

```suggestion
        <input type="text" name="system.attack.bonus" value="{{system.attack.bonus}}" data-formula-editor>
```

2024-02-21 23:23 UTC, arbron approved these changes

2024-03-04 17:37 UTC, Fyorl commented
I think I agree that handling this via the drop-down is not particularly intuitive because the drop-down is labelled 'ability modifier', and this setting controls proficiency bonus and global modifiers too. I wonder, then, if there is any point in the 'None' option anymore? Or are all cases where we might want to set 'Ability Modifier: None' the same cases we we use the 'flat bonus' flag?

2024-03-04 17:58 UTC, Fyorl commented
> I suppose you could theoretically want to add proficiency but not any ability modifier to a roll. Nothing I can think of does that though.

Yeah, ok, well I suppose it doesn't really hurt to have both.

2024-03-04 17:58 UTC, Fyorl approved these changes

2024-03-04 18:54 UTC, merged