Scale spells if they consume slot as resource
foundryvtt/dnd5e pull request #2617
Opened 2023-11-18 15:41 UTC by krbz999

This adds in some changes to resource consumption when a spell is set as innate/atwill but has a spell slot as its resource.

This logic should eventually be able to carry over for other item types that should scale with slots.

2024-04-02 19:50 UTC, Fyorl requested changes

2024-04-02 19:50 UTC, Fyorl commented on templates/apps/ability-use.hbs
> +                {{/each}}
```suggestion
                {{#each resourceOptions}}
                <option value="{{key}}" {{disabled (not canCast)}}>{{label}}</option>
                {{/each}}
```

2024-04-02 19:50 UTC, Fyorl commented on module/applications/item/ability-use-dialog.mjs
> +      resourceArray: Array.isArray(resourceOptions),
Seems `resourceOptions` isn't defined anywhere.

2024-04-02 19:50 UTC, Fyorl commented on module/documents/item.mjs
> +        const isLeveled = /spell[0-9]+/.test(config.slotLevel || "");
I know a lot of these regexes are from existing code but might as well try to clean up a bit as we go along:

```suggestion
        const isLeveled = /spell\d+/.test(config.slotLevel || "");
```

2024-04-02 19:56 UTC, krbz999 commented on module/applications/advancement/item-choice-flow.mjs
> +      if ( !Number.isNaN(level) && (level > slot) ) return level;
It can be undefined, though I suppose that would still mean `data.level > slot` is falsy.

2024-04-03 14:10 UTC, Fyorl approved these changes

2024-04-03 14:11 UTC, merged