[#2698] Move getRollData to system models
foundryvtt/dnd5e pull request #2701
Opened 2023-12-30 23:57 UTC by krbz999

This moves the getRollData to a system method (if it has one).
Also adds `flags` to getRollData, which is a common ask.
Also moves `attributes.spellmod` to data prep where it probably should always have been. \:-)

2023-12-31 08:56 UTC, thatlonelybugbear commented
Consider adding `effects` to the getRollData method, alongside `flags` and you are gonna make many users happy :)

2024-01-18 22:48 UTC, arbron requested changes

2024-01-18 22:48 UTC, arbron commented on module/data/actor/character.mjs
> +  /* -------------------------------------------- */
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

2024-01-18 22:48 UTC, arbron commented on module/data/actor/npc.mjs
> +  /* -------------------------------------------- */
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

2024-01-18 22:48 UTC, arbron commented on module/data/actor/templates/common.mjs
> +  /* -------------------------------------------- */
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

2024-01-18 22:48 UTC, arbron commented on module/data/actor/vehicle.mjs
> +  /* -------------------------------------------- */
```suggestion
  /* -------------------------------------------- */
  /*  Helpers                                     */
  /* -------------------------------------------- */
```

2024-01-18 22:49 UTC, arbron approved these changes

2024-01-18 22:49 UTC, merged