[#2697] Expose actor sheet mixin
foundryvtt/dnd5e pull request #2702
Opened 2023-12-31 00:09 UTC by krbz999

2024-01-01 22:30 UTC, arbron requested changes

2024-01-01 22:30 UTC, arbron commented on module/applications/actor/base-sheet.mjs
> +import {default as ActorSheetMixin} from "./sheet-mixin.mjs";
```suggestion
import ActorSheetMixin from "./sheet-mixin.mjs";
```

2024-01-01 22:30 UTC, arbron commented on module/applications/actor/group-sheet.mjs
> +import {default as ActorSheetMixin} from "./sheet-mixin.mjs";
```suggestion
import ActorSheetMixin from "./sheet-mixin.mjs";
```

2024-01-02 00:44 UTC, arbron approved these changes

2024-01-02 17:30 UTC, Fyorl approved these changes

2024-01-02 17:30 UTC, merged