[#2911] Privatize item roll cards
foundryvtt/dnd5e pull request #2922
Opened 2024-02-06 00:17 UTC by schultzcole

Closes #2911

Observer view on the left, speaker view on the right

![Screenshot_20240205_180750](https://github.com/foundryvtt/dnd5e/assets/1226888/70879207-0df9-4615-a455-5a7188bb750b)

2024-02-06 03:57 UTC, IonPickaxe43 commented
You all rock!

2024-02-06 18:00 UTC, arbron requested changes
I've also noticed that if you click on the total in a hidden message you get an error because it tries to expand a non-existent tooltip. If you move the event listener on `.dice-roll` up a line into the block that should prevent the error.

We should also modify it so it doesn't appear to be clickable. I'd recommend adding a `secret` class to the `roll-total` block if content isn't visible and then tweak the styling to remove the disclosure arrow and use the default cursor rather than the pointer.

2024-02-06 18:00 UTC, arbron commented on module/documents/chat-message.mjs
> +    if ( nameText !== this.user?.name && !subtitle.innerText.length ) subtitle.innerText = this.user?.name ?? "";
```suggestion
    if ( (nameText !== this.user?.name) && !subtitle.innerText.length ) subtitle.innerText = this.user?.name ?? "";
```

2024-02-07 04:48 UTC, arbron approved these changes

2024-02-07 05:07 UTC, merged