[#1871] Add starting equipment advancement
foundryvtt/dnd5e pull request #3045
Opened 2024-02-14 01:02 UTC by arbron

Adds the advancement structure, data model, and placeholder config application for the starting equipment advancement.

<img width="578" alt="Screenshot 2024-02-13 at 17 00 13" src="https://github.com/foundryvtt/dnd5e/assets/19979839/36a6163b-8f37-4d59-b223-d27d4e6ca5b8">

2024-03-05 17:32 UTC, Fyorl requested changes
I have some minor scepticism about putting this in the advancement tab, since it seems it would be simpler to put it in the details tab, obviating the need for concepts like 'supplemental' or 'fake' advancements.

I think I would insist more strongly if there were a clearer delineation of what goes in advancements or not. But, since we have things like racial starting ASIs as advancements, and class starting proficiencies too (for good reason), then no such good delineation exists as far as I can tell.

We might consider a more conceptual grouping when it comes time to redesign the item sheets, i.e. placing starting proficiencies alongside starting equipment somewhere else, even though the former are implemented via advancements 'behind-the-scenes', as it were.

Happy to defer to your judgement for now then, but please see my other (more minor) comments.

2024-03-05 17:36 UTC, arbron commented on module/applications/item/starting-equipment-config.mjs
> +    console.log(event, formData);
Yeah, just a placeholder until the next PR.

2024-03-05 17:40 UTC, arbron commented on module/data/item/templates/starting-equipment.mjs
The label methods are only called if the whole sheet or the configuration app is open, so it seems like it would be less work overall to only call them when rending the sheet, rather than every time the item is prepared.

2024-03-06 21:57 UTC, Fyorl approved these changes
Good stuff, thank you, Jeff

2024-03-06 22:14 UTC, merged