[#893] Add summoning to item activation workflow
foundryvtt/dnd5e pull request #3167
Opened 2024-03-01 19:32 UTC by arbron

Adds summoning configuration to the item usage configuration and the ability use dialog. Players will see a checkbox to indicate whether summoning should occur and if the item has more than one summoning profile, a dropdown for selecting which profile to use:

<img width="413" alt="Summoning Ability Use Dialog" src="https://github.com/foundryvtt/dnd5e/assets/19979839/241b9c31-2bd5-43d8-a90b-d102d9687909">

This also introduces a `prompt` boolean similar to the one used for measured templates and limited uses to control whether it is done by default or not. If the `"Place Summons"` checkbox is checked, then the selected summoning profile ID is stored in flags in the chat message.

A new `"Summon"` button has been added to the chat message to perform the summoning if not done automatically through the ability use process:

<img width="298" alt="Summoning Chat Card" src="https://github.com/foundryvtt/dnd5e/assets/19979839/dabc3623-68ff-4d9d-be79-4e17c422fc3a">

If the button is clicked it will try to summon whatever profile is specified in the flags, or if none is specified it will throw up the ability use dialog again to ask which should be used.

2024-03-01 19:45 UTC, krbz999 commented on module/data/item/templates/action.mjs
> +    return (this.actionType === "summ") && this.summons.profiles.length;
This can return an integer.

2024-03-05 19:28 UTC, Fyorl requested changes
Nice, just one comment for discussion, let me know what you think.

2024-03-05 19:28 UTC, Fyorl commented on module/documents/item.mjs
> +    let summonsProfile = message.getFlag("dnd5e", "use.summonsProfile");
We should consider perhaps not storing the chosen summon profile on the card. I imagine one of the use-cases for clicking the chat card summon button will be that you chose the wrong summon, or want to make a different choice, and it won't be possible to do so with this design, if I understand it correctly.

2024-03-05 22:50 UTC, Fyorl approved these changes

2024-03-06 00:00 UTC, merged