[#3321] Allow spell scrolls to be created at increased level
foundryvtt/dnd5e pull request #3330
Opened 2024-03-23 21:28 UTC by arbron

The `SpellScrollConfiguration` object now has a `level` parameter that causes the created spell scroll to include a spell at a higher level than normal. This stores the increase level information in `flags.dnd5e.spellLevel`, which contains the original leve, the casting level, and the scaling information.

`Item5e#rollDamage` has been modified to now check for the new flag before scaling damage, and use that information if present. The scaling information is stored in the flag because otherwise it would be lost when converting to a consumable type.

2024-03-23 22:30 UTC, krbz999 commented
A "base level" such as this would be good to have for the Tiefling's Hellish Rebuke as well as any magic items that grant spells cast at a level higher than the base. It would be fitting to have this on the Spell data model in general.

2024-03-24 01:16 UTC, arbron commented
> A "base level" such as this would be good to have for the Tiefling's Hellish Rebuke as well as any magic items that grant spells cast at a level higher than the base. It would be fitting to have this on the Spell data model in general.

Probably true, but since created spells scrolls are consumables they don't have level at all so I'll have to do it with flags.

2024-03-28 17:15 UTC, Fyorl requested changes
Just a couple of comments. Maybe we're just being defensive here, but it's possible to pass any garbage for any value of `SpellScrollConfiguration` that `parseInt` won't necessarily protect against, so I think we should just let it fail if bad input is provided.

2024-03-28 17:15 UTC, Fyorl commented on module/documents/item.mjs
> +      originalLevel = parseInt(levelingFlag.base);
Do we need to be lenient with these flag types? Is there any reason they wouldn't necessarily be the correct type already?

```suggestion
      spellLevel = levelingFlag.value;
      originalLevel = levelingFlag.base;
```

2024-03-28 17:15 UTC, Fyorl commented on module/documents/item.mjs
> +      spell.system.level = parseInt(config.level);
`config.level` is annotated as `number`

```suggestion
      flags.dnd5e = { spellLevel: {
        value: config.level,
        base: spell.system.level,
        scaling: spell.system.scaling
      } };
      spell.system.level = config.level;
```

2024-03-28 17:41 UTC, Fyorl approved these changes

2024-03-28 17:42 UTC, merged