Spell preparation limit
foundryvtt/dnd5e pull request #3416
Opened 2024-04-05 11:56 UTC by absymylyar

- Move the spellcasting input to a common template for class and subclass
- Add the "needSpellPreparation" field to spellcasting data
- Calculate and display the spell preparation limit

2024-06-27 17:04 UTC, arbron requested changes

2024-06-27 17:04 UTC, arbron commented on module/documents/item.mjs
> +
This preparation would probably be better handled within the `prepareFinalData` method on class & subclass items. We could add a static method to `SpellcastingField` to perform the calculation and then call that from the class & subclass data models:

Added to `ClassData` and `SubclassData` after the "Data Migrations" section:
```javascript
  /* -------------------------------------------- */
  /*  Data Preparation                            */
  /* -------------------------------------------- */

  /** @inheritDoc */
  prepareFinalData() {
    SpellcastingField.calculatePreparationLimit(this.spellcasting, this.parent.getRollData({ deterministic: true });
  }
```

Added to `SpellcastingField`:
```javascript
  /**
   * Calculate total preparation limit.
   * @param {object} spellcasting  Spellcasting data for this object.
   * @param {object} rollData      Roll data for the actor being prepared.
   */
  static calculatePreparationLimit(spellcasting, rollData) {
    // Calculate preparation limit here using `simplifyBonus` utility
  }
```

```suggestion
```

2024-06-27 17:04 UTC, arbron commented on packs/_source/classes/cleric.json
> +      "needToPrepare": true
```suggestion
      "preparationFormula": "@abilities.wis.mod + @classes.cleric.levels"
```

2024-06-27 17:04 UTC, arbron commented on packs/_source/classes/druid.json
> +      "needToPrepare": true
```suggestion
      "preparationFormula": "@abilities.wis.mod + @classes.druid.levels"
```

2024-06-27 17:04 UTC, arbron commented on packs/_source/classes/paladin.json
> +      "needToPrepare": true
```suggestion
      "preparationFormula": "@abilities.cha.mod + floor(@classes.paladin.levels / 2)"
```

2024-06-27 17:04 UTC, arbron commented on packs/_source/classes/wizard.json
> +      "needToPrepare": true
```suggestion
      "preparationFormula": "@abilities.int.mod + @classes.wizard.levels"
```

2024-06-27 17:04 UTC, arbron commented on templates/items/parts/item-spellcasting.hbs
> +        <input type="checkbox" name="system.spellcasting.needToPrepare" {{ checked system.spellcasting.needToPrepare }}>
```suggestion
        <input type="string" name="system.spellcasting.preparationFormula" value="{{ system.spellcasting.preparationFormula }}">
```

2024-06-27 17:04 UTC, arbron commented on templates/items/parts/item-spellcasting.hbs
> +    <label>{{localize "DND5E.SpellneedToPrepare"}}</label>
```suggestion
    <label>{{ localize "DND5E.SpellPreparation.Formula" }}</label>
```

2024-06-27 17:04 UTC, arbron commented on lang/en.json
> +"DND5E.SpellneedToPrepare": "Need to Prepare Spells",
```suggestion
```

2024-06-27 17:09 UTC, arbron commented
Could you also comment on https://github.com/foundryvtt/dnd5e/issues/1021 & https://github.com/foundryvtt/dnd5e/issues/2978 so I can assign them to you?

2024-07-14 11:26 UTC, absymylyar commented
Sorry, for late reply, I was very busy all those last weeks.
I take all dev in charge back

2024-08-12 21:27 UTC, closed without merging

2024-08-12 21:27 UTC, arbron commented
Modification of this merged: https://github.com/foundryvtt/dnd5e/pull/3811