[#3305] Enforce enchantment restrictions when dropping onto item
foundryvtt/dnd5e pull request #3506
Opened 2024-04-30 18:14 UTC by arbron

When adding an enchantment to an item that accepts enchantments, the restrictions specified in the enchantment source will now be enforced. It will also prevent the creation of an enchantment effect directly on an actor.

Enchanted items in the world will register themselves with a static registry of all enchanted items so the enchantment items can easily determine what items they have enchanted.

Support has been added for items that might offer enchantments or receive them (to support a weapon that can enchant other weapons for example). This uses the `origin` data to track whether the enchantment effect is applied to the item or not. To this end the default origin for new enchantments isn't set like for normal effets. The origin is only set when an enchantment is dragged to another item. This ensures that the enchantment origin always matches the item doing the enchantment, even if that item was duplicated.

2024-04-30 18:44 UTC, krbz999 commented on module/data/item/fields/enchantment-field.mjs
> +  }
This is a neat way of doing it that would also serve concentration effects and other buffs in general well.

2024-04-30 21:11 UTC, Fyorl requested changes
Looks good, thank you Jeff. I noticed some issues around re-rendering the Enchantment Source Item sheet when Items are enchanted, but we can polish that later.

2024-04-30 21:11 UTC, Fyorl commented on module/documents/active-effect.mjs
> +    errors.forEach(err => ui.notifications.error(err.message));
Don't feel great about putting UI notifications inside API code. These should probably be logged to the console, and we should spawn UI notifications at the place the user interaction happens. For enchantments I guess that would be in the Item sheet drop handler, and potentially additional places in the future when we add more ways to enchant Items.

2024-05-03 14:37 UTC, Fyorl approved these changes

2024-05-03 15:26 UTC, merged