Propose resolution to synchronous UUID link generation bug
foundryvtt/dnd5e pull request #3532
Opened 2024-05-05 21:45 UTC by aaclayton

While using the system in V12 (12.231) I encountered a bug where advancement features being pulled from a compendium pack would throw an error and fail to render. You can easily reproduce this by creating a character and attempting to add a class from the compendium pack.

The error was being thrown by the attempted call to `TextEditor._createLegacyContentLink`. I'm not sure why that was deemed necessary.

There is some friction here because now in V12 content link generation is most directly an async operation, but this PR proposes a way to approach the issue using a synchronous workaround that is confirmed to work in V12 and should (but I did not test) work in V11.

2024-05-05 21:49 UTC, aaclayton commented
I've realized there are a couple of issues with this suggestion. I was moving fast and trying to unblock myself, this probably would need some more careful thought to get it to handle all cases properly. Closing the PR.

2024-05-05 22:48 UTC, arbron requested changes

2024-05-05 22:48 UTC, arbron commented on module/utils.mjs
> +    doc = new cls(doc, {pack: collection.metadata.id}); // Build a minimal "shell" of the document using index data
I get a `can't define property "uuid": Object is not extensible` error when loading up a class in the compendium in V12. Deep cloning the data before creating the shell document fixes that:

```suggestion
    // Build a minimal "shell" of the document using index data
    doc = new cls(foundry.utils.deepClone(doc), {pack: collection.metadata.id});
```

2024-05-06 17:40 UTC, arbron approved these changes

2024-05-06 17:58 UTC, merged