fix dynamic token flashing on targeting
foundryvtt/dnd5e pull request #3745
Opened 2024-06-18 18:35 UTC by Drental

targetToken passes the token placeable, so we need to access the token.document to see if the dynamic token ring is enabled

2024-06-19 19:01 UTC, dev7355608 requested changes

2024-06-19 19:01 UTC, dev7355608 commented on module/canvas/token.mjs
> +    if ( !targeted || !token.document.ring?.enabled ) return;
We need to keep the this logic for V11.

```suggestion
    if ( !targeted ) return;
    if ( game.release.generation < 12 ) {
        if ( !token.ring?.enabled ) return;
    } else if ( !token.hasDynamicRing ) return;
```

2024-06-24 17:05 UTC, Drental commented
as a note, I find supporting v11 with the latest release weird, it's more likely to cause issues with v11 versions of modules than it is to improve compatibility overall.

But this PR was just a drive by from trying to showcase uses of the dynamic ring to some other system devs, so I don't really mind the details anyway^^

2024-07-17 19:21 UTC, dev7355608 approved these changes

2024-07-17 19:22 UTC, merged