[#2967] Factor out shared code between PC & NPC sheets. Add item description collapsible sections.
foundryvtt/dnd5e pull request #3796
Opened 2024-07-03 21:16 UTC by Fyorl

- Closes foundryvtt/foundryvtt#2967

Sorry for the size of the PR, a large portion is just code that has been moved without modification, or file renames. I will highlight the sections you can safely skip below:

- `v2/actors.less` has shared code moved from `v2/character.less`.
- `sheet-v2-mixin.mjs` has shared code moved from `character-sheet-2.mjs`
- `actor-classes.hbs` was factored out of `character-features.hbs` (now `creature-features.hbs`)
- `actor-trait-pills.hbs` was factored out of `character-details.hbs`
- All of the `column-*.hbs` files were factored out of `character-features.hbs` (now `creature-features.hbs`)
- `character-spells.hbs` was renamed to `creature-spells.hbs`

`creature-features.hbs` was renamed from `character-features.hbs` but does contain some fairly significant refactoring so is worth a look. `creature-spells.hbs`, `inventory2.hbs` and `creature-features.hbs` show a lot of changes because the item rows needed to be further wrapped in order to support the extra item descriptions, so it's worth taking a quick look at that but otherwise most changes are just whitespace.

2024-07-04 16:41 UTC, arbron requested changes
Looking good.

2024-07-04 16:41 UTC, arbron commented on less/elements.less
> +      text-align: left;
If we wanted to use more logical properties.

```suggestion
      text-align: start;
```

2024-07-04 16:41 UTC, arbron commented on less/v2/inventory.less
> +        .item-summary {
I've noticed that if you don't have a description then the pills get push right up against the rest of the row:

<img width="184" alt="Screenshot 2024-07-04 at 09 19 27" src="https://github.com/foundryvtt/dnd5e/assets/19979839/cc7724f2-aff9-4112-b3b9-ca1a1bbdd95c">

Probably want a bit of padding there to make it a bit more even compared to the bottom padding.

2024-07-04 16:41 UTC, arbron commented on module/applications/actor/sheet-v2-mixin.mjs
> +      const { attributes, traits } = this.actor.system;
`traits` isn't currently being used.

```suggestion
      const { attributes } = this.actor.system;
```

2024-07-04 16:41 UTC, arbron commented on module/applications/actor/sheet-v2-mixin.mjs
> +  }
```suggestion
  };
```

2024-07-04 16:41 UTC, arbron commented on module/applications/actor/sheet-v2-mixin.mjs
> +    /* -------------------------------------------- */
Might be nice to have some separators to distinguish the grouping of methods (e.g. "Rendering" & "Event Listeners & Handlers").

Would involve shifting the `activateListeners` method beneath the other preparation methods.

2024-07-04 16:41 UTC, arbron commented on templates/actors/parts/columns/column-feature-controls.hbs
> +    <a class="item-control interface-only" data-toggle-description
Not hit box of the context menu button seems to overlapping the expand/collapse button making it hard to click in edit mode or on the inventory tab:

<img width="88" alt="Screenshot 2024-07-04 at 09 19 01" src="https://github.com/foundryvtt/dnd5e/assets/19979839/d326969d-7a97-4348-859d-7f664e2f2dc2">

2024-07-04 16:41 UTC, arbron commented on module/utils.mjs
> +    "dnd5e-formatModifier": formatModifier
Would be nice to move this up so these are in alphabetical order (though I suppose `itemContext` is also in the wrong spot :/).

2024-07-04 16:41 UTC, arbron commented on module/utils.mjs
> +function formatModifier(mod) {
This should be up in the "Formatters" grouping new the top of the file.

2024-07-04 16:41 UTC, arbron commented on module/utils.mjs
>      "systems/dnd5e/templates/actors/tabs/character-biography.hbs",
```suggestion
    "systems/dnd5e/templates/actors/tabs/character-biography.hbs",
    "systems/dnd5e/templates/actors/tabs/creature-features.hbs",
    "systems/dnd5e/templates/actors/tabs/creature-spells.hbs",
```

2024-07-04 20:00 UTC, Fyorl commented
Thank you for the feedback, I have addressed it in the latest commit. There are also some additional changes in that commit from more code sharing I factored out today for the biography tab.

2024-07-05 16:29 UTC, arbron approved these changes

2024-07-05 18:33 UTC, merged