Cover status
foundryvtt/dnd5e pull request #4013
Opened 2024-08-20 20:34 UTC by mattexdee

This will allow features which provide cover regardless of position to include an Active Effect that applies the relevant status. It can later be checked in AC calculations and dex saves.

2024-09-11 21:13 UTC, arbron commented
<img width="582" alt="Screenshot 2024-09-11 at 14 10 44" src="https://github.com/user-attachments/assets/a8a6f802-aede-4895-9d25-8c4acb2a697e">

2024-09-11 21:29 UTC, krbz999 commented
Wonder if it would not be cleaner to add a single condition with 3 levels. It should not be too difficult to change the name of the effect at will, and this would also prevent users from applying several different types of cover at the same time.

2024-09-12 14:33 UTC, Fyorl requested changes

2024-09-12 14:33 UTC, Fyorl commented on lang/en.json
> +  "StatusFullCover": "Full Cover",
We should use the game term, which is 'Total Cover'.

2024-09-12 16:53 UTC, arbron commented
> Wonder if it would not be cleaner to add a single condition with 3 levels. It should not be too difficult to change the name of the effect at will, and this would also prevent users from applying several different types of cover at the same time.

I think three statuses is good, because unlike exhaustion you don't cycle through levels of cover, you just apply the one you want directly. What I think I'll add is that when one level of cover is added it removes any current levels of cover.

2024-09-12 18:22 UTC, Fyorl approved these changes

2024-09-12 18:34 UTC, merged