[#4525] Add Facility item & sheet.
foundryvtt/dnd5e pull request #4597
Opened 2024-10-24 19:32 UTC by Fyorl

![image](https://github.com/user-attachments/assets/b0d627d2-9fc5-4273-8cf5-130a43ebee42)

2024-10-24 22:39 UTC, arbron requested changes
Excited!

2024-10-24 22:39 UTC, arbron commented on module/config.mjs
> +DND5E.facilities = {
```suggestion

/**
 * Configuration data for bastion facilities.
 *
 * @typedef {object} FacilityConfiguration
 * @property {Record<string, string>} orders                   Orders that can be issued to a facility.
 * @property {Record<string, string>} sizes                    Size options for a facility.
 * @property {Record<string, SubtypeTypeConfiguration>} types  Facility types and subtypes.
 */

/**
 * Configuration data for bastion facilities.
 * @type {FacilityConfiguration}
 */
DND5E.facilities = {
```

2024-10-24 22:39 UTC, arbron commented on module/data/item/facility.mjs
> +      type: new ItemTypeField({ value: "basic", baseItem: "false" })
```suggestion
      type: new ItemTypeField({ value: "basic", baseItem: false })
```

2024-10-24 22:39 UTC, arbron commented on module/data/item/facility.mjs
> +  /* -------------------------------------------- */
```suggestion
  /* -------------------------------------------- */

  /** @inheritDoc */
  prepareFinalData() {
    this.prepareFinalActivityData(this.parent.getRollData({ deterministic: true }));
  }
```

2024-10-24 22:39 UTC, arbron commented on templates/items/details/details-facility.hbs
> +                         blank="" }}
Feels like this might be better inside the Order section below, and just letting level live on its own line.

2024-10-25 16:03 UTC, krbz999 commented on templates/items/details/details-facility.hbs
> +            {{ formField fields.defenders.fields.max value=source.defenders classes="label-top" placeholder="—" }}
The `value` is incorrect here.

2024-10-25 16:54 UTC, arbron approved these changes
Other than my hint suggestion and the issue Zhell found, everything is looking good.

2024-10-25 16:54 UTC, arbron commented on templates/items/details/details-facility.hbs
> +    <ul class="separated-list facility-craft">
It would be good to have a hint here to indicate that this is the item currently being crafted, not a list of items that can be crafted.

2024-10-25 17:32 UTC, merged