[#4708] Redesign `ItemChoiceConfig` for V2, implement multi-column
foundryvtt/dnd5e pull request #4736
Opened 2024-11-15 23:32 UTC by arbron

Converts `ItemChoiceConfig` to use `ApplicationV2` and the V2 styles. Adds support for multi-column layout within advancement config apps.

<img width="799" alt="Config V2 Choose Items" src="https://github.com/user-attachments/assets/57748174-f296-4bc1-ac8c-a254f7837986">

2024-11-16 00:06 UTC, krbz999 commented on lang/en.json
> +        "hint": "Should players be able to drop their own choices into this advancement?",
Gonna infuriate Unsoluble.

2025-01-10 00:22 UTC, Fyorl requested changes

2025-01-10 00:22 UTC, Fyorl commented on module/applications/api/application-v2-mixin.mjs
> +          div.append(element);
Already done two lines below

```suggestion
```

2025-01-10 00:22 UTC, Fyorl commented on module/applications/api/application-v2-mixin.mjs
> +        const className = config.containerClasses.join(" ");
Using the classes for this seems fragile and also a conflation of concerns. If we want to do something like this I think it would be better to have a separate `container` identifier and `containerClasses`.

2025-01-10 00:22 UTC, Fyorl commented on templates/advancement/item-choice-config-levels.hbs
> +        <span id="{{ partId }}-choices" class="choices-header">
Seems weird to give `<span>`s an `id`. If we're just doing this for the sake of labelling the `<input>`s, can we put an `aria-label` on them directly? Or is there some other benefit to using `aria-labelledby` here?

2025-01-15 22:09 UTC, Fyorl approved these changes

2025-01-15 22:29 UTC, merged