[#4739] Redesign short & long rest dialogs for V2 app & styles
foundryvtt/dnd5e pull request #4743
Opened 2024-11-16 23:37 UTC by arbron

Creates a new `BaseRestDialog` that implements the shared behavior between the two rest dialogs and the new `ShortRestDialog` and `LongRestDialog` inherit from this new application.

<img width="795" alt="Rest Dialogs V2" src="https://github.com/user-attachments/assets/e0685cec-3633-4fdf-87dd-d8a54b778162">

The short rest dialog will now display the "Auto Spend HD" option for all users, not just on the group actor, in case players don't feel like rolling their own hit dice.

Closes #4739

2024-11-16 23:48 UTC, krbz999 commented on module/applications/actor/rest/base-rest-dialog.mjs
> +        { since: "DnD5e 4.1", until: "DnD5e 4.3" }
```suggestion
        { since: "DnD5e 4.2", until: "DnD5e 4.4" }
```

2024-11-16 23:50 UTC, krbz999 commented on module/applications/actor/rest/long-rest-dialog.mjs
> +      { since: "DnD5e 4.1", until: "DnD5e 4.3" }
```suggestion
      { since: "DnD5e 4.2", until: "DnD5e 4.4" }
```

2024-11-16 23:51 UTC, krbz999 commented on module/applications/actor/rest/short-rest-dialog.mjs
> +      { since: "DnD5e 4.1", until: "DnD5e 4.3" }
```suggestion
      { since: "DnD5e 4.2", until: "DnD5e 4.4" }
```

2025-01-07 20:33 UTC, Fyorl requested changes

2025-01-07 22:07 UTC, Fyorl approved these changes

2025-01-07 22:33 UTC, merged