[#4804] Add help icon and tooltip to AE Attribute Key header
foundryvtt/dnd5e pull request #4805
Opened 2024-11-29 17:15 UTC by roth-michael

Closes #4804

2025-01-28 17:35 UTC, roth-michael commented
V13 screenshot:
![image](https://github.com/user-attachments/assets/67316ea5-ccfc-4351-a983-306a29ad21f1)

Don't love where I put the v2 style rule, but couldn't find a more appropriate place.

2025-02-03 18:32 UTC, arbron requested changes

2025-02-03 18:32 UTC, arbron commented on module/documents/active-effect.mjs
> +    const targetElement = html.querySelector("section[data-tab='effects'],section[data-tab='changes'] .key");
This sticks it in the wrong spot in V12, you can add `.key` back to the first part or use `:is` to grab either:

```suggestion
    const targetElement = html.querySelector("section:is([data-tab='effects'],[data-tab='changes']) .key");
```

or

```suggestion
    const targetElement = html.querySelector("section[data-tab='effects'] .key,section[data-tab='changes'] .key");
```

2025-02-03 18:32 UTC, arbron commented on less/v1/apps.less
> +}
A help cursor would be nice here to suggest that hovering will do something.

```suggestion
.active-effect-sheet header.effects-header i {
  margin-left: 0.25rem;
  cursor: help;
}
```

2025-02-03 18:32 UTC, arbron commented on less/v2/apps.less
> +}
```suggestion
.active-effect-config section.changes header div.key i {
  margin-left: 0.25rem;
  cursor: help;
}
```

2025-02-03 18:32 UTC, arbron commented on lang/en.json
> +"DND5E.ActiveEffectAttributeKeyTooltip": "For a list of common keys, see <a href=https://github.com/foundryvtt/dnd5e/wiki/Active-Effect-Guide>the wiki</a>.",
Let's stick this in a nested object. Plus we should be able to handle alternate URLs for enchantments because they have a different set of keys.

```suggestion
"DND5E.ACTIVEEFFECT": {
  "AttributeKeyTooltip": "For a list of common keys, see <a href=\"{url}\">the wiki</a>."
},
```

The ordering here also isn't quite alphabetical, so this should move above the "DND5E.ACTIVITY" line (and leave an extra space surrounding it).

2025-02-03 18:32 UTC, arbron commented on dnd5e.mjs
> +Hooks.on("renderActiveEffectConfig", (app, html, data) => documents.ActiveEffect5e.onRenderActiveEffectConfig(html));
To detect whether this is for an enchantment or not, let's make this an instance method:

```suggestion
Hooks.on("renderActiveEffectConfig", (app, html, data) => app.document.onRenderActiveEffectConfig(html));
```

2025-02-03 18:32 UTC, arbron commented on module/documents/active-effect.mjs
> +  static onRenderActiveEffectConfig(html) {
Non-static so we can grab info on the active effect being displayed. This probably also shouldn't exist under the "Exhaustion and Concentration Handling" heading, so move it down under "Helpers" just beneath `addOverriddenChoices`.

```suggestion
 onRenderActiveEffectConfig(html) {
```

2025-02-03 18:32 UTC, arbron commented on module/documents/active-effect.mjs
> +    const tooltipText = game.i18n.localize("DND5E.ActiveEffectAttributeKeyTooltip");
```suggestion
    const tooltipText = game.i18n.format("DND5E.ACTIVEEFFECT.AttributeKeyTooltip", {
      url: this.type === "enchantment"
        ? "https://github.com/foundryvtt/dnd5e/wiki/Enchantment"
        : "https://github.com/foundryvtt/dnd5e/wiki/Active-Effect-Guide"
    });
```

2025-02-03 19:24 UTC, arbron requested changes

2025-02-03 19:24 UTC, arbron commented on module/documents/active-effect.mjs
> +    const targetElement = html.querySelector("section:is([data-tab='effects'],section[data-tab='changes']) .key");
```suggestion
    const targetElement = html.querySelector("section:is([data-tab='effects'],[data-tab='changes']) .key");
```

2025-02-03 19:53 UTC, roth-michael commented on module/documents/active-effect.mjs
> +    const targetElement = html.querySelector("section:is([data-tab='effects'],section[data-tab='changes']) .key");
Well, good thing at least one of us is paying attention.

2025-08-11 17:55 UTC, Fyorl approved these changes

2025-08-11 17:56 UTC, merged