[#1982] Add support for ranged communication like telepathy
foundryvtt/dnd5e pull request #4875
Opened 2024-12-13 18:31 UTC by arbron

Adds `communication` data to the languages data model that tracks distances and units for features like telepathy.

<img width="830" alt="Ranged Communication" src="https://github.com/user-attachments/assets/561c28ba-50f7-40af-8cd0-de1c58c35798" />

Also includes a large refactor of how trait data models are constructed to match the custom field pattern the system has adopted elsewhere.

Closes #1982

2024-12-13 18:52 UTC, krbz999 commented
Should it not display as "Telepathy | 120" rather than "Telepathy 120 ft" to match senses?

2025-01-03 17:18 UTC, Fyorl requested changes

2025-01-03 17:18 UTC, Fyorl commented on module/data/actor/character.mjs
> + * @typedef {import("./fields/simple-trait.mjs").SimpleTraitData} SimpleTraitData
At least with typedoc, we can use a more ergonomic invocation. Might depend on your IDE whether it works for intellisense or not.

```suggestion
 * @import { SimpleTraitData } from "./fields/simple-trait.mjs";
```

2025-01-03 17:18 UTC, Fyorl commented on module/data/actor/npc.mjs
> +        ].join("; ") || game.i18n.localize("None"),
```suggestion
          })
        ].filterJoin("; ") || game.i18n.localize("None"),
```

2025-01-03 17:18 UTC, Fyorl commented on module/data/actor/templates/traits.mjs
> + * @typedef {import("../fields/simple-trait.mjs").SimpleTraitData} SimpleTraitData
```suggestion
 * @import { DamageTraitData } from "../fields/damage-trait.mjs";
 * @import { SimpleTraitData } "../fields/simple-trait.mjs";
```

2025-01-03 17:18 UTC, Fyorl commented on module/applications/actor/sheet-v2-mixin.mjs
> +        if ( !data?.value ) return;
```suggestion
        if ( !data?.value ) continue;
```

2025-01-03 18:48 UTC, arbron commented on module/data/actor/character.mjs
> + * @typedef {import("./fields/simple-trait.mjs").SimpleTraitData} SimpleTraitData
Our linter doesn't like `@import`, but I can add an exception for that. I was following core's styling for these, but I see you switched things up in V13 :).

2025-01-03 19:21 UTC, Fyorl commented on module/data/actor/character.mjs
> + * @typedef {import("./fields/simple-trait.mjs").SimpleTraitData} SimpleTraitData
I think it was a relatively recent addition to typedoc

2025-01-03 19:27 UTC, Fyorl approved these changes

2025-01-03 19:27 UTC, Fyorl commented on templates/actors/npc-sheet-2.hbs
> -                <div class="pills-group {{#unless speed}}empty{{/unless}}">
Good simplification. We can probably apply it to the actor sheet as well.

2025-01-03 21:05 UTC, merged