[#4787] More informative roll dialog titles
foundryvtt/dnd5e pull request #4884
Opened 2024-12-15 21:27 UTC by roth-michael

Closes #4787 
Also added a check when putting the subtitle for an activity use in a chat card whether the activity was a heal-type, if so display "Healing Roll" instead of "Damage Roll."
Attack Roll:
![image](https://github.com/user-attachments/assets/164978c7-fc9b-48f1-ac32-b963df0637a2)
Damage Roll:
![image](https://github.com/user-attachments/assets/dea83df0-20ae-4c24-bcdc-5cfebbf6e47c)
Skill Check:
![image](https://github.com/user-attachments/assets/d2e25dfa-fa00-4651-b4bc-e481278aad87)
Ability Check: 
![image](https://github.com/user-attachments/assets/8fb24a10-c002-489a-aebe-bae9500ffacf)
Saving Throw:
![image](https://github.com/user-attachments/assets/37c21e17-cc7c-4073-a6d1-8017652a1745)
Tool Check:
![image](https://github.com/user-attachments/assets/43b49afb-5ee9-447d-a05d-5302a321ed7c)
Fixed subtitle for a heal activity:
![image](https://github.com/user-attachments/assets/30c73076-80f1-46d4-89bb-412e7843d080)

2024-12-15 22:23 UTC, roth-michael commented
Might instead make sense to put the roll type in the main title and the actor/item name in the subtitle (if it's okay to lose "Configure Roll" - which I think it would be, since it's implicit).

2024-12-16 00:12 UTC, roth-michael commented
New commit changes to match my last comment.
Skill check:
![Screenshot 2024-12-15 190904](https://github.com/user-attachments/assets/d474eac2-eaf6-452a-b0fb-9e2bc9223fee)
Tool check:
![Screenshot 2024-12-15 191015](https://github.com/user-attachments/assets/dc0cf200-2c1b-433b-a101-e4fed43f2a47)
Damage & Healing rolls:
![Screenshot 2024-12-15 190952](https://github.com/user-attachments/assets/69662629-882a-4651-9378-2e46b60af0a8)
![Screenshot 2024-12-15 191004](https://github.com/user-attachments/assets/c96dcb1c-89ca-4dca-9937-f9cd2bf19151)

2024-12-27 18:13 UTC, arbron commented
@roth-michael Give a comment on the original issue so I can assign it to you

2024-12-27 18:24 UTC, arbron requested changes
Looking good. Might also be nice to show "Concentration Save" when rolling for concentration.

2024-12-27 18:24 UTC, arbron commented on module/documents/activity/mixin.mjs
> +            title: game.i18n.localize(`DND5E.${this.type === "heal" ? "Healing" : "Damage"}Roll`),
You should just `this.damageFlavor` for this. You can change it for the heal activity to use `DND5E.HealingRoll` rather than just `DND5E.Healing`.

2024-12-27 18:24 UTC, arbron commented on module/documents/chat-message.mjs
> +            : game.i18n.localize("DND5E.DamageRoll")
`activity` isn't guaranteed to exist here. We can also use `damageFlavor` here after adjusting the flavor for `HealActivity`:
```suggestion
          ? game.i18n.localize("DND5E.CriticalHit")
          : activity?.damageFlavor ?? game.i18n.localize("DND5E.DamageRoll")
```

2024-12-30 19:35 UTC, roth-michael commented
> Might also be nice to show "Concentration Save" when rolling for concentration

Went with the same label but with `Concentration` instead of `Strength` for instance (i.e. "Concentration Saving Throw"). Was thinking about whether instead "Concentration Save (Con)" would make sense, but as-is it looks fine to me.
![image](https://github.com/user-attachments/assets/e32a41a1-f508-4c32-9ff2-926f99614645)

2024-12-30 19:48 UTC, arbron requested changes
Just the small change about where we set the concentration label, but otherwise looking good.

2024-12-30 19:48 UTC, arbron commented on module/documents/actor/actor.mjs
> +    const abilityLabel = config.isConcentration ? game.i18n.localize("DND5E.Concentration") : CONFIG.DND5E.abilities[config.ability]?.label ?? "";
Move this into the `rollConcentration` method, this method really shouldn't know about the existence of concentration saves as a concept.

2024-12-30 21:17 UTC, arbron approved these changes

2025-01-31 20:58 UTC, Fyorl approved these changes
Good changes.

Would like to change skill titles to more idiomatic language, i.e. 'Acrobatics Skill Check' -> 'Dexterity (Acrobatics) Check' (and the resulting chat flavour text). But that would involve having the window title update based on what's chosen in the ability drop-down. No idea how involved that would be without trying it out first.

2025-01-31 22:55 UTC, roth-michael commented
I suspect it wouldn't be too bad - except for the case where `chooseAbility` is true - though I wonder whether it'd feel a bit cramped. Will give it a go tomorrow and see.

2025-02-01 19:33 UTC, roth-michael commented
![image](https://github.com/user-attachments/assets/5b86112c-aafb-4cf4-a9f5-7129e493f77e)
Actually doesn't look cramped. If it looks good to you I'll push it. Realized `chooseAbility` is always gonna be on currently, so I think no problem with just leaving the title by whatever the default on the rolling actor's sheet should be.

2025-02-01 20:09 UTC, roth-michael commented
This would be the, uh, "clever" way I came up with:

```js
/** @inheritDoc */
_onChangeForm(formConfig, event) {
  super._onChangeForm(formConfig, event);
  if ( this.config.skill ) {
    const skillLabel = CONFIG.DND5E.skills[this.config.skill]?.label ?? "";
    const ability = this.form.querySelector('select[name="ability"]')?.value ?? this.config.ability;
    const abilityLabel = CONFIG.DND5E.abilities[ability]?.label ?? "";
    this.window.title.innerText = game.i18n.format("DND5E.SkillPromptTitle", { skill: skillLabel, ability: abilityLabel });
  }
}
```

inside `SkillToolRollConfigurationDialog`

2025-02-03 14:25 UTC, Fyorl commented
> This would be the, uh, "clever" way I came up with:
> 
> ```js
> /** @inheritDoc */
> _onChangeForm(formConfig, event) {
>   super._onChangeForm(formConfig, event);
>   if ( this.config.skill && event.target?.name === "ability" ) {
>     const skillLabel = CONFIG.DND5E.skills[this.config.skill]?.label ?? "";
>     const ability = event.target.value ?? this.config.ability;
>     const abilityLabel = CONFIG.DND5E.abilities[ability]?.label ?? "";
>     this.window.title.innerText = game.i18n.format("DND5E.SkillPromptTitle", { skill: skillLabel, ability: abilityLabel });
>   }
> }
> ```
> 
> inside `SkillToolRollConfigurationDialog`
> 
> ~Ah. One more issue with including the selected ability in the title: the title (based on the `config`) is also used for the roll flavor in the chat card. So would need to account for that as well somehow so the proper flavor is used.~ Easily fixed by setting `this.message.data.flavor` to the same thing as the title in the above snippet.

Yeah that looks good. It's doing the same thing, but you could use `ApplicationV2#_updateFrame` which is maybe slightly more future-proofed.

```js
/** @inheritDoc */
_onChangeForm(formConfig, event) {
  super._onChangeForm(formConfig, event);
  if ( this.config.skill && (event.target?.name === "ability") ) {
    const skillLabel = CONFIG.DND5E.skills[this.config.skill]?.label ?? "";
    const ability = event.target.value ?? this.config.ability;
    const abilityLabel = CONFIG.DND5E.abilities[ability]?.label ?? "";
    this._updateFrame({
      window: { title: game.i18n.format("DND5E.SkillPromptTitle", { skill: skillLabel, ability: abilityLabel }) }
    });
  }
}
```

2025-02-03 15:44 UTC, Fyorl approved these changes

2025-02-03 15:44 UTC, merged