Extend rider conditions to generic effects
foundryvtt/dnd5e pull request #4886
Opened 2024-12-15 23:27 UTC by krbz999

When an effect granted to a target by some monster feature means that you also suffer from a given condition (eg "while slimed, you are also considered Poisoned"), that effect should simply have the given status. This use case is covered well enough and improved slightly by #4881.

The other case is being affected by a generic condition *in addition* - eg "you are slimed, and also knocked prone," where the two effects/conditions are independent; they are applied at the same time but can be removed at different times. This PR helps with that specific use case.

2025-02-04 16:11 UTC, Fyorl requested changes
Code looks good but we should try to improve the wording if we can. At the moment, the user will just see two multi-selects with the same options. The second multi-select says they are 'additional conditions that will be applied when this effect is created on actor', but from the point of view of the user, the statuses in the first multi-select are also 'applied' when the AE is created. As far as they can tell, the effect is created, and the actor gets all the statuses in both multi-selects.

So we need some way to make it clearer that the first multi-select is 'connected' to the effect, while the second multi-select isn't. There's probably a better word to use than 'connected', not sure. If it helps, we should add a hint to the first multi-select also, and/or change the label test.

2025-02-04 18:57 UTC, krbz999 commented
> So we need some way to make it clearer that the first multi-select is 'connected' to the effect, while the second multi-select isn't. There's probably a better word to use than 'connected', not sure. If it helps, we should add a hint to the first multi-select also, and/or change the label text.

Should we just get rid of it? Does the `statuses` input field have a good and well-defined purpose in this system?

2025-02-04 19:07 UTC, Fyorl commented
> Should we just get rid of it? Does the `statuses` input field have a good and well-defined purpose in this system?

You explained it yourself in the first paragraph of this PR's description, no?

> When an effect granted to a target by some monster feature means that you also suffer from a given condition (eg "while slimed, you are also considered Poisoned"), that effect should simply have the given status.

Am I misunderstanding?

2025-02-04 19:40 UTC, Fyorl commented
> Maybe we should just have a custom AE sheet at this point tho.

Yeah, that's certainly on the table. I'd expect the system to end up with a custom AE sheet eventually anyway.

2025-02-05 01:20 UTC, krbz999 commented
![image](https://github.com/user-attachments/assets/295128c4-c5e1-4978-8f7f-a315df94d1ec)

2025-02-05 14:01 UTC, Fyorl commented on lang/en.json
> +      "label": "Status Conditions",
In v13 the label disappeared unless I duplicated it here. Not sure why.

2025-02-05 14:02 UTC, Fyorl commented on module/documents/active-effect.mjs
> +      html.querySelector(".form-fields:has([name=statuses])").insertAdjacentHTML("afterend", `
In v13 this was being appended twice because the localisation hint was already being applied by the core application. I guess that's not working in v12? Worth checking if appending this is even necessary.

2025-02-05 14:03 UTC, Fyorl approved these changes
Had to make some adjustments for v13 but otherwise it looks good. Let me know if it's still good in v12 with these adjustments, and then we can merge.

2025-02-05 14:40 UTC, krbz999 commented
Still looks good in v12.

2025-02-05 14:40 UTC, krbz999 commented on module/documents/active-effect.mjs
> +      html.querySelector(".form-fields:has([name=statuses])").insertAdjacentHTML("afterend", `
There is no `hint` in v12 if that is what you mean?

2025-02-05 14:42 UTC, krbz999 commented on lang/en.json
> +      "label": "Status Conditions",
Probably because it does not merge.

https://github.com/foundryvtt/foundryvtt/issues/11489

I should have remembered that.

2025-02-05 14:50 UTC, Fyorl commented on module/documents/active-effect.mjs
> +      html.querySelector(".form-fields:has([name=statuses])").insertAdjacentHTML("afterend", `
I mean the localisation prefix wasn't applying the hint in v12. Maybe it's a v13-only feature. I've been on v13 so long I don't remember.

2025-02-05 14:51 UTC, merged

2025-02-05 14:55 UTC, krbz999 commented on module/documents/active-effect.mjs
> +      html.querySelector(".form-fields:has([name=statuses])").insertAdjacentHTML("afterend", `
In v12, it doesn't use `{{formGroup}}`.
```html
        <div class="form-group">
            <label>Status Conditions</label>
            <div class="form-fields">
                <multi-select name="statuses">
                    {{#each statuses as |status|}}
                    <option value="{{status.id}}" {{status.selected}}>{{status.label}}</option>
                    {{/each}}
                </multi-select>
            </div>
        </div>
```