[#3667] Add grouping to initiative tracker
foundryvtt/dnd5e pull request #4897
Opened 2024-12-17 19:37 UTC by arbron

Adds automatic grouping to the initiative tracker. This will group any combatants with the same initiative and the same base actor into a group.

<img width="308" alt="Combat Groups - Collapsed" src="https://github.com/user-attachments/assets/5ff4c72b-0e3d-4590-9952-7e1c9bd52882" />
<img width="310" alt="Combat Groups - Expanded" src="https://github.com/user-attachments/assets/9fe72e1a-e41e-479c-ab46-3459d31b0c39" />

Groups are displayed as collapsible sections in the combat tracker that use the name from the base actor's prototype token. It lists the number of combatants in the group, and when one of the group members is active it displays how far through the group that actor is.

Currently only offers the one grouping mode, but could be expanded in the future to support different grouping such as splitting it into "friendly" and "hostile" groups.

Also works in V13:

<img width="307" alt="Screenshot 2024-12-20 at 12 26 37" src="https://github.com/user-attachments/assets/86ddbfa7-5904-4e54-a749-295deb4c4bba" />

Closes #3667

2024-12-17 20:05 UTC, krbz999 commented
> This will group any combatants with the same initiative and the same base actor into a group.

What about:
- `TokenDocument#disposition`
- `PrototypeToken#actorLink`
- `TokenDocument#name`

It's quite common to use a generic monster for a one-off NPC. Steve the Quest Giver Goblin the party rescues from a cage surely shouldn't be grouped with the rest of them.

2024-12-17 22:43 UTC, arbron commented
> > This will group any combatants with the same initiative and the same base actor into a group.
> 
> What about:
> 
> * `TokenDocument#disposition`
> * `PrototypeToken#actorLink`
> * `TokenDocument#name`
> 
> It's quite common to use a generic monster for a one-off NPC. Steve the Quest Giver Goblin the party rescues from a cage surely shouldn't be grouped with the rest of them.

We could take disposition & actor link into account (probably never group if actor link is true), but we wouldn't want to use the token name otherwise adding numbers or adjectives like the goblins in the screenshots above would prevent them from ever being grouped.

2024-12-18 19:38 UTC, MaxPat931 commented
Is this intended to work best with flat initiative per #4812 or are there plans for streamlining the process of setting init values for a group, re:
> The DM makes one roll for an entire group of identical creatures

2025-01-28 15:48 UTC, Fyorl requested changes
Looks good to me, just spotted one thing that needs adjustment.

It might also be nice to extend the core hover functionality somewhat, assuming core makes it possible to do so. If you hover a token on the scene, the corresponding combatant is highlighted. If that combatant is in a collapsed group, it would be nice to highlight the group they belong to. Not required in this PR though.

2025-01-28 15:48 UTC, Fyorl commented on module/applications/combat/combat-tracker.mjs
> +      if ( activeEntry !== undefined ) {
```suggestion
      if ( activeEntry ) {
```

2025-01-28 15:48 UTC, Fyorl commented on module/applications/combat/combat-tracker.mjs
> +              ${game.i18n.format("DND5E.COMBAT.Group.Title", { name })}
This name needs to be appended safely in case it contains HTML.

2025-01-28 22:27 UTC, arbron commented on module/applications/combat/combat-tracker.mjs
> +      if ( activeEntry !== undefined ) {
Active entry is the index, so `0` is a valid value.

2025-01-30 21:25 UTC, Fyorl approved these changes

2025-01-30 22:39 UTC, merged