[#4873] Fix enricher pattern to be able to contain ] symbol in item name
foundryvtt/dnd5e pull request #4904
Opened 2024-12-19 01:53 UTC by Greatshock

2024-12-27 18:05 UTC, arbron commented
You'll have to rebase this on the `4.2.x` branch because there have been adjustments to this regex already.

2024-12-27 19:46 UTC, Greatshock commented
> You'll have to rebase this on the `4.2.x` branch because there have been adjustments to this regex already.

conflicts resolved

2024-12-28 21:22 UTC, arbron requested changes

2024-12-28 21:22 UTC, arbron commented on module/enrichers.mjs
> +    pattern: new RegExp(`\\[\\[/(?<type>${stringNames.join("|")})(?<config> .*?)?]](?!\])(?:{(?<label>[^}]+)})?`, "gi"),
```suggestion
    pattern: new RegExp(`\\[\\[/(?<type>${stringNames.join("|")})(?<config> .*?)?]](?!])(?:{(?<label>[^}]+)})?`, "gi"),
```

2024-12-28 21:22 UTC, arbron approved these changes

2024-12-28 21:23 UTC, merged