Evaluate or replace formula data when applying effects or enchantments
foundryvtt/dnd5e pull request #4907
Opened 2024-12-19 15:33 UTC by krbz999

Proof-of-concept PR on how the system might use roll data from a caster on a target or other evaluated values.

Related issues: #3809, #4437, #4464, #4465

When granting an effect or enchantment via the effect trays, if `ActiveEffect#flags.dnd5e.application.mode` is `"evaluate"`, then the effect will attempt to retrieve roll data from the origin and use a copy of the `changes` array where the values are fully evaluated (dice rolls performed if needed); if it's `"replace"`, then roll data in the values are simply replaced with the caster's, allowing the target to make use of it.

2024-12-19 16:48 UTC, roth-michael commented on module/documents/active-effect.mjs
> +    if ( !this.origin || this.origin.startsWith("Compendiun.") ) return null;
`Compendiun` -> `Compendium`

2024-12-20 11:58 UTC, tposney commented
Very nice - I can rip out most of the guts of dae if this goes in.

2026-03-02 23:54 UTC, krbz999 commented
Most of this can probably be ripped out with v14 since "replace" doesnt need to exist as an option.

2026-03-02 23:58 UTC, arbron commented
I was thinking about this the other day and how we might be able to use a custom `changes` data model in V14 to do this without the flag. We could have an option for each change allowing creators to specify whether that specific change is evaluated before application using either the granter's roll data or the grantee's.

With V14 we don't have to worry about using formulas to apply to number fields, but even for formula fields which don't pre-evaluate in V14 we still might want to resolve rolled values on application in case the field is deterministic.

For your note in limitations above about not being able to share a value between fields, you could always start with a change to a flag that resolves the value and then the other changes can just reference that flag.

2026-07-20 17:47 UTC, arbron requested changes

2026-07-20 17:47 UTC, arbron commented on module/data/abstract/active-effect-data-model.mjs
>        conditions: new FiltersField()
```suggestion
      conditions: new FiltersField(),
      replacement: new StringField({
        required: true,
        blank: true,
        choices: {
          origin: "DND5E.EFFECT.Replacement.Origin",
          target: "DND5E.EFFECT.Replacement.Target"
        }
      })
```

2026-07-20 17:47 UTC, arbron commented on module/documents/activity/enchant.mjs
> +    const originData = this.getRollData();
Since we need to do this in multiple places, why don't we move the actual replacement process into `ActiveEffect5e`. We could either add a new method to create an effect ready to be applied (`effect.forApplication(target, { origin })`), or by adding new options to the `clone` method (`effect.clone({}, { application: { target, origin } })`).

2026-07-20 19:23 UTC, krbz999 commented on module/documents/activity/enchant.mjs
> +    const originData = this.getRollData();
Like mentioned in the desc it would be good (perhaps in a followup) to evaluate dice formulas, so it should be async imo. I think I would opt for a static `ActiveEffect5e.forApplication` method that creates just the `changes`.

2026-07-21 23:47 UTC, arbron requested changes
One other place we'll also want to handle this is in the `ApplyActiveEffect5eRegionBehaviorType`. If the region it belongs to was created by an activity, then the `dnd5e.activity` (recently renamed) flag on the region will get the creating activity, though we'll have to make sure it handles manually created regions that won't have origin data.

2026-07-21 23:47 UTC, arbron commented on module/documents/active-effect.mjs
> +   * @returns {Promise<object[]>}     A promise that resolves to the modified change data.
To clarify that neither of these are required.

```suggestion
   * @param {object[]} changes         Effect change data in json-serializable format.
   * @param {*} [origin]               The origin of the effect to be applied.
   * @param {Actor5e|Item5e} [target]  The target of the effect to be applied.
   * @returns {Promise<object[]>}      A promise that resolves to the modified change data.
```

2026-08-15 23:16 UTC, Fyorl approved these changes

2026-08-19 00:15 UTC, merged