[#4861] Add combat activation types that display in turn message
foundryvtt/dnd5e pull request #4911
Opened 2024-12-20 19:38 UTC by arbron

Adds three new activation types in a new "Combat" section: "Start of Encounter", "Start of Turn", and "End of Turn". These activation types will display in the combat chat message with a "Use" button to be easily activated. They also have a tooltip to display the full item description on hover.

The turn chat message stores relative UUIDs of the activiations in its data model to avoid having to check all of the actor's items every time the chat message is rendered.

Closes #4861

2024-12-20 22:31 UTC, krbz999 commented on module/documents/combatant.mjs
> +    console.log(this.actor, periods, messageConfig.data.system.activations);
Gezundheit.

2025-01-04 00:10 UTC, Fyorl requested changes
In addition to my comments I noticed a couple of issues while testing:

- It seems that `turnStart` is not fired for the first combatant of the combat when the combat is started. When I tested this I had only one combatant in the combat and they had rolled initiative. This might be a core v12 bug though.
- Giving an activity one of the new combat activations puts them in the 'actions' section on the NPC features tab if 'group by origin' is enabled. Notably this is distinct from the 'action' section where all other actions are. I think there's still a todo for pluralising those section titles, but I think this issue is unrelated, and that combat activations should probably be sorted into the 'features' section (that we should also rename to 'traits' at some point).

2025-01-04 00:10 UTC, Fyorl commented on templates/chat/turn-card.hbs
> +                </button>
This button looks a bit chunky in-line compared to our other in-line button style in the case of applying effects from the effects tray. I was thinking of using a single icon and making it smaller to match the effects tray icon, but an icon to represent 'use' might be a bit abstract.

Could we instead remove this button and give the item header the `rollable` class instead? Clicking an item header is pretty well established in the system by now as a way to 'use' it I think. That also frees up the right-hand side in case we want to put something else there (maybe charges or something).

2025-01-04 01:31 UTC, arbron commented on module/data/chat-message/turn-message-data.mjs
> +      .flat();
`Collection` doesn't have `flatMap`.

2025-01-04 01:44 UTC, arbron commented
> * It seems that `turnStart` is not fired for the first combatant of the combat when the combat is started. When I tested this I had only one combatant in the combat and they had rolled initiative. This might be a core v12 bug though.

Had to move it from `nextTurn` to `_onStartTurn` & `_onEndTurn`, which also fixes a potential issue with players pressing the "Next Turn" button and creating chat messages for combatants they don't own.

I've realized we might have a bug with updating the dynamic ring during combat, because it looks like it only updates for the user who presses the "Next Turn" button. Might need to move that code into the `Combat5e._onUpdate` to ensure it is called for all clients.

2025-01-06 15:05 UTC, Fyorl approved these changes

2025-01-06 15:13 UTC, merged