[#3617] Add enchantment effect for modifying damage types
foundryvtt/dnd5e pull request #4913
Opened 2024-12-20 23:04 UTC by arbron

Adds the ability for enchantments to replace or add to the damage types for all parts on an activity. This is done using an active effect targeting `system.damage.types`. Using the `OVERRIDE` mode will replace all existing damage types with the specified type, while `ADD` will introduce a new damage type to the existing types.

Closes #3617

2025-01-20 19:21 UTC, arbron commented
> There are some changes here which seem to allow the activity sheet to show various parts of consumption/recovery/damage that have been added via enchantment, but I'm not sure how sustainable this approach is.
> 
> What if an enchantment modifies something that's not in a parts collection? We have the same problem as with AEs, no? The field can't show both the source and modified versions simultaneously.
> 
> Do we add an edit lock to activity sheets as well? Or we could instead consider the activity sheet an edit-only sheet, and enchantment modifications show up only in prepared views of the activity, such as Actor sheets? Or do we restrict enchantment modifications only to various parts collections of an activity?

A big issue I was trying to resolve here was what to do with damage parts, because I want to show the original version of any part that is changed by enchantment, but I also need to show the base weapon damage part which isn't in the source data.

Perhaps we can treat them as edit-only sheets for now and just have some special handling for damage parts to display enchantment-added parts as locked.

2025-01-20 20:14 UTC, Fyorl requested changes

2025-01-20 20:14 UTC, Fyorl commented on module/applications/activity/activity-sheet.mjs
> +        prefix: `damage.parts.${index}.`,
Seems to result in the base damage part having a name of `damage.parts.undefined.`. Seemed to work ok when I tested, but perhaps not intentional.

2025-01-20 23:22 UTC, arbron commented on module/applications/activity/activity-sheet.mjs
> +        prefix: `damage.parts.${index}.`,
Before it was `damage.parts.-1` for base damage, so long as it isn't a valid array index it should be fine.

2025-01-31 19:08 UTC, Fyorl approved these changes

2025-01-31 20:03 UTC, merged