Add advantage modes to `abilities` objects
foundryvtt/dnd5e pull request #4922
Opened 2024-12-25 00:04 UTC by krbz999

(Built on top of #4890.)

Adds `system.abilities.<abilityId>.check.roll` and `.save.roll` objects.

Moves the derived `abilities.<abilityId>.save` value into `.check/.save.value` with a `toString` method for the deprecation period.

(Also removes the `ability` property from the `attributes.death` object.)

2024-12-26 00:16 UTC, JPMeehan commented
Wasn't there a discussion that for AEs to work properly you probably should split dis & adv so that way the cancelling can be parsed correctly?

2024-12-26 00:49 UTC, krbz999 commented
> Wasn't there a discussion that for AEs to work properly you probably should split dis & adv so that way the cancelling can be parsed correctly?

See the AdvantageModeField.

2024-12-26 01:02 UTC, JPMeehan commented
Those are properties on the shared model schema – does this not have collisions across multiple actors of the same type?

2024-12-26 09:16 UTC, krbz999 commented
> Those are properties on the shared model schema – does this not have collisions across multiple actors of the same type?

I don't see why - the field is reset when initialized, and actors don't share the same instance of a DataField.

2024-12-26 18:33 UTC, JPMeehan commented
![image](https://github.com/user-attachments/assets/8f9eaa2e-3df7-4b33-9b30-2692beaf92c0)

Fields are properties of the static class - `myModel.schema` accesses `myModel.constructor.schema`. That's why all of the field methods like _cast take in the data they're modifying.

2024-12-27 17:57 UTC, arbron reviewed
Seems like a good start 👍

2024-12-27 17:57 UTC, arbron commented on module/data/actor/templates/common.mjs
> + * @property {number} save.roll.max     The maximum that can be rolled on the d20.
```suggestion
 * @property {object} check          Properties related to ability checks.
 * @property {RollConfigData} check.roll
 * @property {object} save           Properties related to ability saving throws.
 * @property {RollConfigData} save.roll
```

2024-12-27 17:57 UTC, arbron commented on module/data/actor/templates/common.mjs
> +        })
```suggestion
        check: new RollConfigField({ ability: false }),
        save: new RollConfigField({ ability: false })
```

2025-01-02 23:24 UTC, arbron requested changes

2025-01-02 23:24 UTC, arbron commented on module/data/shared/roll-config-field.mjs
> + * @typedef {object} RollConfigFieldData
Make sure you update other usages of this if you are renaming it, it is referenced in `actor/templates/creature.mjs`.

2025-01-02 23:24 UTC, arbron commented on module/data/shared/roll-config-field.mjs
> +    }
You can follow this pattern which we have used in `MovementField` and elsewhere to allow for deleting fields (add the field back above of course). I find it a bit more readable to define all of the fields in the same way:

```suggestion
   Object.entries(fields).forEach(([k, v]) => !v ? delete fields[k] : null);
```

2025-01-02 23:35 UTC, krbz999 commented on module/data/shared/roll-config-field.mjs
> + * @typedef {object} RollConfigFieldData
Had misread those same ones, should not have been renamed.

2025-01-02 23:40 UTC, arbron commented on module/data/shared/roll-config-field.mjs
> +      ability: ( ability === false ) ? null : new StringField({
You won't need the check here, because the `...fields` at the end will replace this with `false` for you.

2025-01-02 23:46 UTC, krbz999 commented on module/data/shared/roll-config-field.mjs
> +      ability: ( ability === false ) ? null : new StringField({
How so? We destructure the property because it should be `""` if omitted.

2025-01-02 23:49 UTC, arbron commented on module/data/shared/roll-config-field.mjs
> +      ability: ( ability === false ) ? null : new StringField({
Aw, yeah, I forgot you are also using `ability` to set the default value as well as to remove the field. Ignore me.

2025-01-02 23:49 UTC, arbron approved these changes

2025-01-06 20:42 UTC, YenBenGrey commented
Apologies if this is completely the wrong place to put this, however there is a tenuous link. (not sure if you can make an issue for a PR)

If this gets implemented, would it be possible for the advantage, disadvantage buttons to be clearer/brighter/shinier rather then a thin red line around the button like it shows for a normal hit and none crit damage.

2025-01-06 21:52 UTC, krbz999 commented
> If this gets implemented, would it be possible for the advantage, disadvantage buttons to be clearer/brighter/shinier rather then a thin red line around the button like it shows for a normal hit and none crit damage.

Would be a separate issue.

2025-01-27 16:08 UTC, Fyorl approved these changes

2025-01-27 16:08 UTC, merged